Fix markdown extension error.
<Config value: 'markdown_extensions'. Error: Failed to initiate extension 'math': 'module' object has no attribute 'makeExtension'>
probably the naming convention is changed and had to be fixed, see
<https://python-markdown.github.io/change_log/release-2.5/>.